# Generated by Django 4.0.1 on 2022-03-16 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=10)),
                ('level', models.CharField(choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('500', 'Level 500'), ('600', 'Level 600')], default='', max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('staff_id', models.IntegerField(default=0)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('aggregated_score_computed_value', models.FloatField(default=0, editable=False)),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('9f581d9b-5b5d-4d11-a6b7-02c2e5799897'), null=True, unique=True)),
                ('deadline', models.DateTimeField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facilitator')),
            ],
            options={
                'verbose_name_plural': 'Evaluation Reports',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facilitator'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program'),
        ),
        migrations.CreateModel(
            name='EvaluationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_feedback_beginning_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_course_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_lecture_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_outcomes_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_procedures_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('curriculum_feedback_books_answer', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_schedule', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_punctuality', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('attendance_presence', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_enthusiasm', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_sequence', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_organization', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_clarity', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_contents', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_responsiveness', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_achievements', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_innovation', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('delivery_theory_practices', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_relevance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_promptitude', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_feedback', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('assignments_guidance', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_availability', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_help', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('interaction_fairness', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_classroom_size', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_seats', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_audio_visual_equip', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_public_address', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_books', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_computers', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_internet', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_air_conditioning', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('environment_secretariat', models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Moderately Disagree'), (4, 'Agree'), (5, 'Strongly Agree')], default=None)),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('a063175d-849b-4330-bd63-78266c557672'), null=True, unique=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('evaluationInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evaluations', to='core.evaluation')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
            options={
                'unique_together': {('submitter', 'evaluationInfo')},
            },
        ),
    ]